### ISSUE TITLE
Proposal: Enhancement to fsutil

### ISSUE THREAD

**Issue by majenkotech** [RetroBSD/retrobsd#13]
At the moment fsutil creates files in a filesystem in a very basic manner.  It takes the file mode of the existing file on disk and uses that for the mode, and sets all UIDs and GIDs to 0.

I propose a modification to how filenames are handled by fsutil so that a filename can contain data about how it should be added.  Something like, instead of just

    $ fsutil -a filesys.img sbin/su

you can have something like

    $ fsutil -a filesys.img sbin/su@uid=0,gid=0,mode=4755

Everything after the @ is taken as file parameters for creating the file in the right way.

The idea behind having the data as part of the filename is twofold:

1. It doesn't rely on any special permissions by the user to achieve things like SUID root, and
2. Files can be created on disk then added with their permissions etc using a simple "find" command.

**Comment by sergev** [comment]
Seems like all the requested functionality is already supported using manifest files. With manifest files, it's possible to set all the required attributes, like owner and group ID, access mode, device major and minor indexes, symlink path etc.
