### ISSUE TITLE
PIC32-PINGUINO-MICRO makefile target missing

### ISSUE THREAD

**Issue by DanKoloff** [RetroBSD/retrobsd#50]
PIC32-PINGUINO-MICRO (with PIC32MX795F512H) is listed as supported.  I am not sure which is the suitable TARGET in the makefile. Such TARGET configuration is present in some of the stable branches.

Also I couldn't find any pre-built binaries for download. While I understand that it is impossible to compile binaries for each commit or repository change for all boards, I'm sure a lot of people would benefit from read-to-upload binaries. Even if these are not available at GitHub probably such can be made available somewhere around the RetroBSD http://retrobsd.org/wiki/

With best wishes,
Dan

**Comment by sergev** [comment]
Fixed in https://github.com/RetroBSD/retrobsd/commit/229b664f354fdb8fa59df32d67d11e7151558f53
Added a kernel configuration for Olimex PIC32-PINGUINO-MICRO board with MX795 chip. 
An auto-build server is planned with fresh retrobsd binaries to be available for download.

**Comment by sergev** [comment]
Hi Dan,
An autobuild server is ready.
Now you can always download a latest binary for your board from the RetroBSD web site: http://retrobsd.org/wiki/autobuild.php
Regards,
--Serge
