### ISSUE TITLE
Virus editor, strlcpy error

### ISSUE THREAD

**Issue by cratuki** [RetroBSD/retrobsd#79]
When I am in vi, I use ":e filename" to open a new file. The file does not exist yet. I get this error,

"vi: strlcpy overflow in function colon: Unknown error: 0a segment".

I built retrobsd from current master (9d8ad7ccf588d08bfa7eb7063ed1920fa19116f5) using the mentor graphics toolchain (see issue 78).

**Comment by cratuki** [comment]
This also manifests when the file does exist. Looks like ':e' is generally broken in vi.

**Comment by sergev** [comment]
Hi Craig,
Thank you for the bug report. Looks like the bug was inherited from original Virus sources. The editor crashed when colon command line exceeded a size of a pointer (4 bytes in case of RetroBSD). Fixed in a0c256c1f0129ee6eb0d00f385e98da9b28d94c1.

**Comment by cratuki** [comment]
Thanks for that. I spent about half an hour playing to try and get virus compiled on my native system, so I could compare it, unsuccessfully.

In your diff, I notice the linux/__APPLE_ clauses. Is there an easy way to get the code to compile for native?

[Quick praise, since the forum has closed. I have spent most of the weekend tapping away to get up to speed with RetroBSD (pinguino unit) and LiteBSD (emz64). My original goal was to use the tooling on one of them to bootstrap a forth operating system. Not sure now. Good to read through code for your portable forth. Also the kernel source. Often C code disappears under macros. But there is a beautiful init_main in the retrobsd source, and you can just read the steps.]

**Comment by cratuki** [comment]
Confirmed fix.

**Comment by sergev** [comment]
> In your diff, I notice the linux/__APPLE_ clauses. Is there an easy way to get the code to compile for native?

With my changes, the virus.c can be easily compiled natively on Mac or Linux, like:
```
cc virus.c -o virus -ltermcap
```
Add -lbsd on Linux.

> [Quick praise, since the forum has closed. I have spent most of the weekend tapping away to get up to speed with RetroBSD (pinguino unit) and LiteBSD (emz64). My original goal was to use the tooling on one of them to bootstrap a forth operating system. Not sure now. Good to read through code for your portable forth. Also the kernel source. Often C code disappears under macros. But there is a beautiful init_main in the retrobsd source, and you can just read the steps.]

Thank you, Craig. For me, BSD has always been an inspiration and amazing example of how much can be achieved with low resources but proper system design.
